# Generated by Django 3.0.5 on 2020-04-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollution_index',
            name='city',
            field=models.CharField(default='s', max_length=20),
            preserve_default=False,
        ),
    ]
