# Generated by Django 3.0.5 on 2020-04-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_pollution_index_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollution_index',
            name='area',
            field=models.CharField(default='s', max_length=20),
            preserve_default=False,
        ),
    ]
